App/urls.py
from django.conf.urls import url
from App import views

app_name = 'App'

urlpatterns = [
    url(r'^run/$', views.run, name='run'),
    url(r'^monitor/$', views.monitor, name='monitor'),
    url(r'^delete_job/(?P<task_id>.+)/$', views.delete_job, name='delete_job'),
    url(r'^cancel_job/(?P<task_id>.+)/$', views.cancel_job, name='cancel_job')
]

AsyncDjangoApp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^App/', include('App.urls')), # our application !
]

App/models.py
from django.db import models


class Tasks(models.Model):
    task_id = models.CharField(max_length=50)
    job_name = models.CharField(max_length=50)

    def __str__(self):
        return 'testt'

App/forms.py
from django import forms


class JobForm(forms.Form):
    job_name = forms.CharField(label='Job name', required=True)

App/views.py
from App.tasks import process
from App.models import Tasks
from App.forms import JobForm
from django.shortcuts import render
from celery.result import AsyncResult
from django.views.decorators.http import require_http_methods, require_GET


@require_http_methods(["GET", "POST"])
def run(request):
    if request.method == "POST":
        form = JobForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            job_name = data['job_name']
            #Tasks.objects.create(task_id=1, job_name=job_name)
            process.delay(job_name=job_name)
            return render(request, 'job.html',
                          context={'form': JobForm,
                                   'message': job_name})
    else:
        return render(request, 'job.html', context={'form': JobForm})


def track_jobs():
    entries = Tasks.objects.all()
    information = []
    for item in entries:
        progress = 100  # max value for bootstrap progress bar, when the job is finished
        result = AsyncResult(item.task_id)
        if isinstance(result.info, dict):
            progress = result.info['progress']
        information.append([item.job_name, result.state, progress, item.task_id])
    return information

@require_GET
def monitor(request):
    info = track_jobs()
    return render(request, 'monitor.html', context={'info': info})

@require_GET
def cancel_job(request, task_id=None):
    result = AsyncResult(task_id)
    result.revoke(terminate=True)
    info = track_jobs()
    return render(request, 'monitor.html', context={'info': info})


@require_GET
def delete_job(request, task_id=None):
    a = Tasks.objects.filter(task_id=task_id)
    a.delete()
    info = track_jobs()
    return render(request, 'monitor.html', context={'info': info})

templates/job.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
        <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    </head>
    <body>
        <div class="container d-flex justify-content-center">
            <div class="jumbotron text-center col-md-7">
                <p><i>{{ message }}</i></p>
                <form action="{% url 'App:run' %}" method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                <button type="submit" class="btn-primary">Run</button>
                </form>
                <a href="{% url 'App:monitor' %}">
                    <button class="btn-info">Monitor</button>
                </a>
            </div>
        </div>
    </body>
</html>

templates/monitor.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
        <link rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    </head>
    <body>
        <div class="container d-flex justify-content-center">
            <div class="jumbotron text-center col-md-7">
                <table>
                    <tbody>
                    {% for job_name, state, progress, task_id in info %}
                        <tr>
                            <td>{{ job_name }}</td>
                            <td style="width:100%;">
                                <div class="progress" >
                                    <div class="progress-bar" role="progressbar" style="width: {{ progress }}%"
                                         aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100">{{ state }}
                                    </div>
                                </div>
                            </td>
                            <td><a href="{% url 'App:delete_job' task_id=task_id %}">
                                <button class="btn-warning">Delete</button></a>
                            </td>
                            <td><a href="{% url 'App:cancel_job' task_id=task_id %}">
                                <button class="btn-danger">Cancel</button></a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            <a href="{% url 'App:run' %}"><button class="btn-dark">Back</button></a>
            </div>
        </div>
    </body>
</html>